name = "AllanFit"
uuid = "53e018d8-0c24-42d9-a7e0-fac71f608dfb"
authors = ["Gabriel Nunes <nunesgfs@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"

[extras]
AllanDeviations = "7e732cdd-9a46-54ef-932c-559ab8d83ddb"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "PyPlot", "AllanDeviations"]
